// Surah metadata — all 114 surahs
export interface SurahMeta {
  number: number;
  name: string;           // Arabic name
  englishName: string;    // Transliterated
  englishMeaning: string; // English meaning
  ayahs: number;
  type: "Meccan" | "Medinan";
}

export const SURAHS: SurahMeta[] = [
  { number: 1,   name: "الفاتحة",       englishName: "Al-Fatihah",      englishMeaning: "The Opening",          ayahs: 7,   type: "Meccan" },
  { number: 2,   name: "البقرة",        englishName: "Al-Baqarah",      englishMeaning: "The Cow",               ayahs: 286, type: "Medinan" },
  { number: 3,   name: "آل عمران",      englishName: "Aal-E-Imran",     englishMeaning: "The Family of Imran",   ayahs: 200, type: "Medinan" },
  { number: 4,   name: "النساء",        englishName: "An-Nisa",         englishMeaning: "The Women",             ayahs: 176, type: "Medinan" },
  { number: 5,   name: "المائدة",       englishName: "Al-Maidah",       englishMeaning: "The Table Spread",      ayahs: 120, type: "Medinan" },
  { number: 6,   name: "الأنعام",       englishName: "Al-Anam",         englishMeaning: "The Cattle",            ayahs: 165, type: "Meccan" },
  { number: 7,   name: "الأعراف",       englishName: "Al-Araf",         englishMeaning: "The Heights",           ayahs: 206, type: "Meccan" },
  { number: 8,   name: "الأنفال",       englishName: "Al-Anfal",        englishMeaning: "The Spoils of War",     ayahs: 75,  type: "Medinan" },
  { number: 9,   name: "التوبة",        englishName: "At-Tawbah",       englishMeaning: "The Repentance",        ayahs: 129, type: "Medinan" },
  { number: 10,  name: "يونس",          englishName: "Yunus",           englishMeaning: "Jonah",                 ayahs: 109, type: "Meccan" },
  { number: 11,  name: "هود",           englishName: "Hud",             englishMeaning: "Hud",                   ayahs: 123, type: "Meccan" },
  { number: 12,  name: "يوسف",          englishName: "Yusuf",           englishMeaning: "Joseph",                ayahs: 111, type: "Meccan" },
  { number: 13,  name: "الرعد",         englishName: "Ar-Rad",          englishMeaning: "The Thunder",           ayahs: 43,  type: "Medinan" },
  { number: 14,  name: "إبراهيم",       englishName: "Ibrahim",         englishMeaning: "Abraham",               ayahs: 52,  type: "Meccan" },
  { number: 15,  name: "الحجر",         englishName: "Al-Hijr",         englishMeaning: "The Rocky Tract",       ayahs: 99,  type: "Meccan" },
  { number: 16,  name: "النحل",         englishName: "An-Nahl",         englishMeaning: "The Bee",               ayahs: 128, type: "Meccan" },
  { number: 17,  name: "الإسراء",       englishName: "Al-Isra",         englishMeaning: "The Night Journey",     ayahs: 111, type: "Meccan" },
  { number: 18,  name: "الكهف",         englishName: "Al-Kahf",         englishMeaning: "The Cave",              ayahs: 110, type: "Meccan" },
  { number: 19,  name: "مريم",          englishName: "Maryam",          englishMeaning: "Mary",                  ayahs: 98,  type: "Meccan" },
  { number: 20,  name: "طه",            englishName: "Ta-Ha",           englishMeaning: "Ta-Ha",                 ayahs: 135, type: "Meccan" },
  { number: 21,  name: "الأنبياء",      englishName: "Al-Anbiya",       englishMeaning: "The Prophets",          ayahs: 112, type: "Meccan" },
  { number: 22,  name: "الحج",          englishName: "Al-Hajj",         englishMeaning: "The Pilgrimage",        ayahs: 78,  type: "Medinan" },
  { number: 23,  name: "المؤمنون",      englishName: "Al-Muminun",      englishMeaning: "The Believers",         ayahs: 118, type: "Meccan" },
  { number: 24,  name: "النور",         englishName: "An-Nur",          englishMeaning: "The Light",             ayahs: 64,  type: "Medinan" },
  { number: 25,  name: "الفرقان",       englishName: "Al-Furqan",       englishMeaning: "The Criterion",         ayahs: 77,  type: "Meccan" },
  { number: 26,  name: "الشعراء",       englishName: "Ash-Shuara",      englishMeaning: "The Poets",             ayahs: 227, type: "Meccan" },
  { number: 27,  name: "النمل",         englishName: "An-Naml",         englishMeaning: "The Ant",               ayahs: 93,  type: "Meccan" },
  { number: 28,  name: "القصص",         englishName: "Al-Qasas",        englishMeaning: "The Stories",           ayahs: 88,  type: "Meccan" },
  { number: 29,  name: "العنكبوت",      englishName: "Al-Ankabut",      englishMeaning: "The Spider",            ayahs: 69,  type: "Meccan" },
  { number: 30,  name: "الروم",         englishName: "Ar-Rum",          englishMeaning: "The Romans",            ayahs: 60,  type: "Meccan" },
  { number: 31,  name: "لقمان",         englishName: "Luqman",          englishMeaning: "Luqman",                ayahs: 34,  type: "Meccan" },
  { number: 32,  name: "السجدة",        englishName: "As-Sajdah",       englishMeaning: "The Prostration",       ayahs: 30,  type: "Meccan" },
  { number: 33,  name: "الأحزاب",       englishName: "Al-Ahzab",        englishMeaning: "The Combined Forces",   ayahs: 73,  type: "Medinan" },
  { number: 34,  name: "سبإ",           englishName: "Saba",            englishMeaning: "Sheba",                 ayahs: 54,  type: "Meccan" },
  { number: 35,  name: "فاطر",          englishName: "Fatir",           englishMeaning: "Originator",            ayahs: 45,  type: "Meccan" },
  { number: 36,  name: "يس",            englishName: "Ya-Sin",          englishMeaning: "Ya Sin",                ayahs: 83,  type: "Meccan" },
  { number: 37,  name: "الصافات",       englishName: "As-Saffat",       englishMeaning: "Those Ranged in Ranks", ayahs: 182, type: "Meccan" },
  { number: 38,  name: "ص",             englishName: "Sad",             englishMeaning: "The Letter Sad",        ayahs: 88,  type: "Meccan" },
  { number: 39,  name: "الزمر",         englishName: "Az-Zumar",        englishMeaning: "The Groups",            ayahs: 75,  type: "Meccan" },
  { number: 40,  name: "غافر",          englishName: "Ghafir",          englishMeaning: "The Forgiver",          ayahs: 85,  type: "Meccan" },
  { number: 41,  name: "فصلت",          englishName: "Fussilat",        englishMeaning: "Explained in Detail",   ayahs: 54,  type: "Meccan" },
  { number: 42,  name: "الشورى",        englishName: "Ash-Shuraa",      englishMeaning: "The Consultation",      ayahs: 53,  type: "Meccan" },
  { number: 43,  name: "الزخرف",        englishName: "Az-Zukhruf",      englishMeaning: "The Ornaments of Gold", ayahs: 89,  type: "Meccan" },
  { number: 44,  name: "الدخان",        englishName: "Ad-Dukhan",       englishMeaning: "The Smoke",             ayahs: 59,  type: "Meccan" },
  { number: 45,  name: "الجاثية",       englishName: "Al-Jathiyah",     englishMeaning: "The Crouching",         ayahs: 37,  type: "Meccan" },
  { number: 46,  name: "الأحقاف",       englishName: "Al-Ahqaf",        englishMeaning: "The Wind-Curved Sandhills", ayahs: 35, type: "Meccan" },
  { number: 47,  name: "محمد",          englishName: "Muhammad",        englishMeaning: "Muhammad",              ayahs: 38,  type: "Medinan" },
  { number: 48,  name: "الفتح",         englishName: "Al-Fath",         englishMeaning: "The Victory",           ayahs: 29,  type: "Medinan" },
  { number: 49,  name: "الحجرات",       englishName: "Al-Hujurat",      englishMeaning: "The Rooms",             ayahs: 18,  type: "Medinan" },
  { number: 50,  name: "ق",             englishName: "Qaf",             englishMeaning: "The Letter Qaf",        ayahs: 45,  type: "Meccan" },
  { number: 51,  name: "الذاريات",      englishName: "Adh-Dhariyat",    englishMeaning: "The Winnowing Winds",   ayahs: 60,  type: "Meccan" },
  { number: 52,  name: "الطور",         englishName: "At-Tur",          englishMeaning: "The Mount",             ayahs: 49,  type: "Meccan" },
  { number: 53,  name: "النجم",         englishName: "An-Najm",         englishMeaning: "The Star",              ayahs: 62,  type: "Meccan" },
  { number: 54,  name: "القمر",         englishName: "Al-Qamar",        englishMeaning: "The Moon",              ayahs: 55,  type: "Meccan" },
  { number: 55,  name: "الرحمن",        englishName: "Ar-Rahman",       englishMeaning: "The Beneficent",        ayahs: 78,  type: "Medinan" },
  { number: 56,  name: "الواقعة",       englishName: "Al-Waqiah",       englishMeaning: "The Inevitable",        ayahs: 96,  type: "Meccan" },
  { number: 57,  name: "الحديد",        englishName: "Al-Hadid",        englishMeaning: "The Iron",              ayahs: 29,  type: "Medinan" },
  { number: 58,  name: "المجادلة",      englishName: "Al-Mujadila",     englishMeaning: "The Pleading Woman",    ayahs: 22,  type: "Medinan" },
  { number: 59,  name: "الحشر",         englishName: "Al-Hashr",        englishMeaning: "The Exile",             ayahs: 24,  type: "Medinan" },
  { number: 60,  name: "الممتحنة",      englishName: "Al-Mumtahanah",   englishMeaning: "She That is to be Examined", ayahs: 13, type: "Medinan" },
  { number: 61,  name: "الصف",          englishName: "As-Saf",          englishMeaning: "The Ranks",             ayahs: 14,  type: "Medinan" },
  { number: 62,  name: "الجمعة",        englishName: "Al-Jumuah",       englishMeaning: "Friday",                ayahs: 11,  type: "Medinan" },
  { number: 63,  name: "المنافقون",     englishName: "Al-Munafiqun",    englishMeaning: "The Hypocrites",        ayahs: 11,  type: "Medinan" },
  { number: 64,  name: "التغابن",       englishName: "At-Taghabun",     englishMeaning: "The Mutual Disillusion", ayahs: 18, type: "Medinan" },
  { number: 65,  name: "الطلاق",        englishName: "At-Talaq",        englishMeaning: "The Divorce",           ayahs: 12,  type: "Medinan" },
  { number: 66,  name: "التحريم",       englishName: "At-Tahrim",       englishMeaning: "The Prohibition",       ayahs: 12,  type: "Medinan" },
  { number: 67,  name: "الملك",         englishName: "Al-Mulk",         englishMeaning: "The Sovereignty",       ayahs: 30,  type: "Meccan" },
  { number: 68,  name: "القلم",         englishName: "Al-Qalam",        englishMeaning: "The Pen",               ayahs: 52,  type: "Meccan" },
  { number: 69,  name: "الحاقة",        englishName: "Al-Haqqah",       englishMeaning: "The Reality",           ayahs: 52,  type: "Meccan" },
  { number: 70,  name: "المعارج",       englishName: "Al-Maarij",       englishMeaning: "The Ascending Stairways", ayahs: 44, type: "Meccan" },
  { number: 71,  name: "نوح",           englishName: "Nuh",             englishMeaning: "Noah",                  ayahs: 28,  type: "Meccan" },
  { number: 72,  name: "الجن",          englishName: "Al-Jinn",         englishMeaning: "The Jinn",              ayahs: 28,  type: "Meccan" },
  { number: 73,  name: "المزمل",        englishName: "Al-Muzzammil",    englishMeaning: "The Enshrouded One",    ayahs: 20,  type: "Meccan" },
  { number: 74,  name: "المدثر",        englishName: "Al-Muddaththir",  englishMeaning: "The Cloaked One",       ayahs: 56,  type: "Meccan" },
  { number: 75,  name: "القيامة",       englishName: "Al-Qiyamah",      englishMeaning: "The Resurrection",      ayahs: 40,  type: "Meccan" },
  { number: 76,  name: "الإنسان",       englishName: "Al-Insan",        englishMeaning: "The Man",               ayahs: 31,  type: "Medinan" },
  { number: 77,  name: "المرسلات",      englishName: "Al-Mursalat",     englishMeaning: "The Emissaries",        ayahs: 50,  type: "Meccan" },
  { number: 78,  name: "النبإ",         englishName: "An-Naba",         englishMeaning: "The Tidings",           ayahs: 40,  type: "Meccan" },
  { number: 79,  name: "النازعات",      englishName: "An-Naziat",       englishMeaning: "Those Who Drag Forth",  ayahs: 46,  type: "Meccan" },
  { number: 80,  name: "عبس",           englishName: "Abasa",           englishMeaning: "He Frowned",            ayahs: 42,  type: "Meccan" },
  { number: 81,  name: "التكوير",       englishName: "At-Takwir",       englishMeaning: "The Overthrowing",      ayahs: 29,  type: "Meccan" },
  { number: 82,  name: "الانفطار",      englishName: "Al-Infitar",      englishMeaning: "The Cleaving",          ayahs: 19,  type: "Meccan" },
  { number: 83,  name: "المطففين",      englishName: "Al-Mutaffifin",   englishMeaning: "The Defrauding",        ayahs: 36,  type: "Meccan" },
  { number: 84,  name: "الانشقاق",      englishName: "Al-Inshiqaq",     englishMeaning: "The Sundering",         ayahs: 25,  type: "Meccan" },
  { number: 85,  name: "البروج",        englishName: "Al-Buruj",        englishMeaning: "The Mansions of Stars", ayahs: 22,  type: "Meccan" },
  { number: 86,  name: "الطارق",        englishName: "At-Tariq",        englishMeaning: "The Morning Star",      ayahs: 17,  type: "Meccan" },
  { number: 87,  name: "الأعلى",        englishName: "Al-Ala",          englishMeaning: "The Most High",         ayahs: 19,  type: "Meccan" },
  { number: 88,  name: "الغاشية",       englishName: "Al-Ghashiyah",    englishMeaning: "The Overwhelming",      ayahs: 26,  type: "Meccan" },
  { number: 89,  name: "الفجر",         englishName: "Al-Fajr",         englishMeaning: "The Dawn",              ayahs: 30,  type: "Meccan" },
  { number: 90,  name: "البلد",         englishName: "Al-Balad",        englishMeaning: "The City",              ayahs: 20,  type: "Meccan" },
  { number: 91,  name: "الشمس",         englishName: "Ash-Shams",       englishMeaning: "The Sun",               ayahs: 15,  type: "Meccan" },
  { number: 92,  name: "الليل",         englishName: "Al-Layl",         englishMeaning: "The Night",             ayahs: 21,  type: "Meccan" },
  { number: 93,  name: "الضحى",         englishName: "Ad-Duhaa",        englishMeaning: "The Morning Hours",     ayahs: 11,  type: "Meccan" },
  { number: 94,  name: "الشرح",         englishName: "Ash-Sharh",       englishMeaning: "The Relief",            ayahs: 8,   type: "Meccan" },
  { number: 95,  name: "التين",         englishName: "At-Tin",          englishMeaning: "The Fig",               ayahs: 8,   type: "Meccan" },
  { number: 96,  name: "العلق",         englishName: "Al-Alaq",         englishMeaning: "The Clot",              ayahs: 19,  type: "Meccan" },
  { number: 97,  name: "القدر",         englishName: "Al-Qadr",         englishMeaning: "The Power",             ayahs: 5,   type: "Meccan" },
  { number: 98,  name: "البينة",        englishName: "Al-Bayyinah",     englishMeaning: "The Clear Proof",       ayahs: 8,   type: "Medinan" },
  { number: 99,  name: "الزلزلة",       englishName: "Az-Zalzalah",     englishMeaning: "The Earthquake",        ayahs: 8,   type: "Medinan" },
  { number: 100, name: "العاديات",      englishName: "Al-Adiyat",       englishMeaning: "The Courser",           ayahs: 11,  type: "Meccan" },
  { number: 101, name: "القارعة",       englishName: "Al-Qariah",       englishMeaning: "The Calamity",          ayahs: 11,  type: "Meccan" },
  { number: 102, name: "التكاثر",       englishName: "At-Takathur",     englishMeaning: "The Rivalry in World Increase", ayahs: 8, type: "Meccan" },
  { number: 103, name: "العصر",         englishName: "Al-Asr",          englishMeaning: "The Declining Day",     ayahs: 3,   type: "Meccan" },
  { number: 104, name: "الهمزة",        englishName: "Al-Humazah",      englishMeaning: "The Traducer",          ayahs: 9,   type: "Meccan" },
  { number: 105, name: "الفيل",         englishName: "Al-Fil",          englishMeaning: "The Elephant",          ayahs: 5,   type: "Meccan" },
  { number: 106, name: "قريش",          englishName: "Quraysh",         englishMeaning: "Quraysh",               ayahs: 4,   type: "Meccan" },
  { number: 107, name: "الماعون",       englishName: "Al-Maun",         englishMeaning: "The Small Kindnesses",  ayahs: 7,   type: "Meccan" },
  { number: 108, name: "الكوثر",        englishName: "Al-Kawthar",      englishMeaning: "The Abundance",         ayahs: 3,   type: "Meccan" },
  { number: 109, name: "الكافرون",      englishName: "Al-Kafirun",      englishMeaning: "The Disbelievers",      ayahs: 6,   type: "Meccan" },
  { number: 110, name: "النصر",         englishName: "An-Nasr",         englishMeaning: "The Divine Support",    ayahs: 3,   type: "Medinan" },
  { number: 111, name: "المسد",         englishName: "Al-Masad",        englishMeaning: "The Palm Fibre",        ayahs: 5,   type: "Meccan" },
  { number: 112, name: "الإخلاص",       englishName: "Al-Ikhlas",       englishMeaning: "The Sincerity",         ayahs: 4,   type: "Meccan" },
  { number: 113, name: "الفلق",         englishName: "Al-Falaq",        englishMeaning: "The Daybreak",          ayahs: 5,   type: "Meccan" },
  { number: 114, name: "الناس",         englishName: "An-Nas",          englishMeaning: "The Mankind",           ayahs: 6,   type: "Meccan" },
];

export function searchSurahs(query: string): SurahMeta[] {
  if (!query.trim()) return SURAHS;
  const q = query.toLowerCase().trim();
  const num = parseInt(q);
  return SURAHS.filter(s =>
    s.englishName.toLowerCase().includes(q) ||
    s.englishMeaning.toLowerCase().includes(q) ||
    s.name.includes(q) ||
    (!isNaN(num) && s.number === num)
  );
}